name: Release TBB binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux,windows]
        goarch: [amd64,arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -p=1 -timeout=0 ./...
      - uses: wangyoucao577/go-release-action@v1.26
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "whatsapp-audiobot"
          ldflags: "-s -w"
          extra_files: LICENSE Readme.md

     # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          tags: |
            mmaks17/whatsapp-audiobot:latest 
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}         
          
          
